### ISSUE TITLE
No animation between routes with the same template

### ISSUE THREAD

**Issue by Baukereg** [ember-animation/liquid-fire#424] opened 2016-01-26 12:17 UTC
I have two routes with transition animations using Liquid Fire. Works fine!
But since both route templates are identical, I created one generic template and applied them to both routes using renderTemplate. Works fine as well, but sadly breaks the animation.

I quess Liquid Fire doesn't really animate between routes but between templates instead.

**Comment by Cryrivers** [comment] 2016-01-27 02:35
this is mentioned before. you should use `liquid-bind` instead of `liquid-outlet` in your case.

**Comment by ef4** [comment] 2016-01-27 02:56
I think two issues are being slightly confused.

Model-to-model transitions on a single route definitely require `liquid-bind` instead of `liquid-outlet`.

But @Baukereg's original bug report is different, and likely a duplicate of https://github.com/ember-animation/liquid-fire/issues/18

**Closed by ef4** 2016-01-27 02:56 UTC
