### ISSUE TITLE
Liquid Outlet Bug

### ISSUE THREAD

**Issue by shoxter** [ember-animation/liquid-fire#600] opened 2018-02-11 18:34 UTC
I'm getting the following error:

`"Cannot set property timestamp of function VelocityFN()"`

At this line:

```
  // Velocity's tick() defaults to RAF's high resolution timestamp. If the browser
  // is under high stress the RAF timestamp may have a significant offset which
  // can result in dropping a large chunk of frames. Because of this, the use of
  // the RAF timestamp should be opt-in.
  /* jshint newcap: false */
  _velocity.default.timestamp = false;
```

This is a brand new project and this error occurs the moment I change the application outlet to a liquid outlet.

**Comment by shoxter** [comment] 2018-02-11 20:55
UPDATE: 

This isn't just for `liquid-outlet`.

I also tried using a `liquid-bind` and I got the same error.

Is LF not compatible with the latest version of Ember?

**Comment by shoxter** [comment] 2018-02-12 12:54
Here is my package.json's dependencies:

```
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~2.18.2",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.1.1",
    "ember-cli-sass": "^7.1.4",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-composable-helpers": "^2.1.0",
    "ember-concurrency": "^0.8.14",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-paper": "^1.0.0-beta.4",
    "ember-resolver": "^4.0.0",
    "ember-route-action-helper": "^2.0.6",
    "ember-source": "~2.18.0",
    "ember-welcome-page": "^3.0.0",
    "eslint-plugin-ember": "^5.0.0",
    "liquid-fire": "^0.29.1",
    "loader.js": "^4.2.3"
  }
```

**Comment by shoxter** [comment] 2018-02-12 19:44
@ef4 Would it help if I got in a slack call or something with you?

I want to get this problem resolved and I'm fairly certain it is not something special about my project.

Thanks in advance!

**Comment by ef4** [comment] 2018-02-12 19:59
I copied your list into a new app and I still can't reproduce.

Have you tried removing all your node_modules and reinstalling them. I know that is lame, but it is sadly also sometimes effective.

**Comment by shoxter** [comment] 2018-02-12 20:01
I'll do that right now and let you know.

Thanks for troubleshooting this with me. I can't for the life of me imagine what it is on a brand new project.

I use it in many of our other projects, so it's quite strange.

**Comment by shoxter** [comment] 2018-02-12 20:05
Still no luck... :(

Could it be that I'm using yarn as our dependency manager?

Or possibly something to do with HiDPI resolution monitors?

I'm shooting in the dark here, but I'd love to help.

**Comment by ef4** [comment] 2018-02-12 20:15
No, it's probably not yarn or hidpi. 

Have you tried multiple browsers? Does this effect all of them?

**Comment by shoxter** [comment] 2018-02-12 20:16
I've tried Firefox and Chrome and both have the same issue.

Unfortunately, I develop on Mint Linux so I cannot try Edge or IE.

**Comment by ef4** [comment] 2018-02-12 20:21
If you can tar up your `dist` folder and share it with me I can take a look. Email is fine, mine is public on my github profile.

**Comment by shoxter** [comment] 2018-02-12 20:22
Perfect. Thank you very much for your help. Sending it now.

**Comment by ef4** [comment] 2018-02-12 20:50
So it appears you got a much newer version of the velocity-animate package than I did when I did a fresh app install (you have 2.0.1, I have 1.5.1). I don't know why I didn't also get 2.0, but that seems to be the culprit. 

Assuming https://github.com/ember-animation/liquid-fire/pull/603 passes CI I will merge and release that so you can see if that solves your problem.

**Comment by shoxter** [comment] 2018-02-12 20:53
That's so awesome man. Thank you so much.

I'll keep an eye on it passing and test it ASAP and get back to you.

**Comment by ef4** [comment] 2018-02-12 21:16
Ok, try 0.29.2.

**Comment by shoxter** [comment] 2018-02-12 21:18
The error is gone. I'll keep you posted if there's anything else, but I suspect that was exclusively it.

Thanks again Edward.

**Comment by scottkidder** [comment] 2018-07-26 17:14
This appears to be fixed. Let's close it :+1:

**Closed** 2018-08-27 03:16 UTC
